"""Pydantic schemas for the chat API."""

from typing import Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Incoming chat message from the frontend / client."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="User's natural-language weather query.",
        examples=["Will it rain in Mumbai tomorrow?"],
    )
    location: Optional[str] = Field(
        default=None,
        max_length=120,
        description="Optional location context (city, district, or lat,lon).",
        examples=["Mumbai"],
    )
    language: Optional[str] = Field(
        default="en-IN",
        max_length=10,
        description="BCP-47 language code for the reply (default en-IN).",
        examples=["hi-IN"],
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {"message": "Will it rain in Mumbai tomorrow?", "location": "Mumbai"}
            ]
        }
    }


class ChatResponse(BaseModel):
    """Outgoing response returned to the client."""

    reply: str = Field(
        ...,
        description="Natural-language answer generated by the WeatherGPT agent.",
    )
    alert_level: str = Field(
        default="Green",
        description="IMD-style alert level: Green, Yellow, Orange, or Red.",
        examples=["Green"],
    )
    language: str = Field(
        default="en-IN",
        description="BCP-47 language code the reply is written in, echoed from the request.",
        examples=["hi-IN"],
    )
